.gitignore, .gitpod.yml, Makefile
=> Initial commit and gitpodfyzation

.gitpod.yml
=> Configure jsonnet vscode extension

.theia/settings.json
=> Fix jsonnet extension config

.theia/settings.json, Makefile, build.sh, grafana.jsonnet, o11y-stack.jsonnet
Signed-off-by: arthursens <arthursens2005@gmail.com>
=> Playing around with kube-prometheus customizations

.gitpod.yml
=> Change gitpod workspace image to add some extra useful tools

.github/workflows/jsonnetfmt.yml, jsonnet/alertmanager.libsonnet
=> Test github action

jsonnet/homemade-alertmanager.libsonnet, jsonnet/main.jsonnet
=> Remove namespace from prometheus and alertmanager pod names

Makefile, addons/preview-env.libsonnet, hack/deploy.sh
=> Preview-env prometheus filter ServiceMonitors by namespace

Makefile, addons/cluster-monitoring.libsonnet, hack/build.sh, monitoring-central.jsonnet
=> Add monitoring-central jsonnet

Makefile, addons/disable-grafana-auth.libsonnet, addons/grafana-on-gcp-oauth.libsonnet, main.jsonnet
Tested and deployed https://monitoring.gitpod-dev.com 🚀 
Fixes #26
=> Fixes from tests

main.jsonnet, monitoring-central.jsonnet
=> Add jsonnet script focused on monitoring-central

components/gitpod/gitpod.libsonnet, components/gitpod/mixin/alerts.libsonnet, components/gitpod/mixin/mixin.libsonnet, components/gitpod/mixin/rules.libsonnet, main.jsonnet
Follow up work: 
* Write the runbook URL
* Update dashboard queries to use the recording rule
=> Alerting and recording rules for login SLO

addons/cluster-monitoring.libsonnet, addons/node-affinity.libsonnet, addons/preview-env.libsonnet, main.jsonnet
=> Add node affinity for full cluster monitoring addon

addons/gitpod-runbooks.libsonnet, main.jsonnet
=> Override kube-prometheus runbook URLs

components/gitpod/mixin/dashboards/components/ws-daemon.json
=> Fix ws-daemon dashboard variables

components/gitpod/mixin/dashboards.libsonnet, components/gitpod/mixin/dashboards/SLOs/policy.json, components/gitpod/mixin/dashboards/components/agent-smith.json
Policy SLO:
Component / Agent-Smith:
=> Update Agent-smith dashboard with the new implemented metrics

main.jsonnet
=> Increase CPU limits for node-exporter, grafana and kube-state-metrisc

components/gitpod/mixin/prometheus_rules.yaml, components/gitpod/mixin/rules.libsonnet, components/gitpod/mixin/rules/SLO/SLOs.libsonnet, components/gitpod/mixin/rules/SLOs.libsonnet, components/gitpod/mixin/rules/components/components.libsonnet, components/gitpod/mixin/rules/components/nodes/alerts.libsonnet, components/gitpod/mixin/rules/components/nodes/mixin.libsonnet, runbooks/GitpodMetaCPUSaturation.md, runbooks/GitpodMetaNodesOOMKills.md
=> Add OOM Kills and CPU Saturation alerts

components/gitpod/mixin/prometheus_rules.yaml, components/gitpod/mixin/rules/SLO/login/alerts.libsonnet, lib/alert-severity-mapper.libsonnet
=> Change Login SLO and node disk space alerts severity

components/gitpod/mixin/dashboards/gitpod-overview.json
=> Add missing cluster filter to gitpod overview

components/gitpod/gitpod.libsonnet
<a href="https://gitpod.io/#https://github.com/gitpod-io/observability/pull/86"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added containerd-metrics

addons/slack-alerting.libsonnet, components/gitpod/mixin/prometheus_rules.yaml, components/gitpod/mixin/rules/SLO/login/alerts.libsonnet, lib/alert-severity-mapper.libsonnet
Fixes #85 
<a href="https://gitpod.io/#https://github.com/gitpod-io/observability/pull/87"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Critical alerts to be routed to both Slack and PagerDuty
